const strings = {
  english: {
    welcomeMessage: "Welcome to the AIquiz!",
    topicPlaceholder: "Topic",
    startButton: "Start",
    loading: "Loading",
    correctAnswers: "Correct Answers:",
  },
  chinese: {
    welcomeMessage: "欢迎来到 AI 测验！",
    topicPlaceholder: "主题",
    startButton: "开始",
    loading: "加载中",
    correctAnswers: "正确答案：",
  },
  spanish: {
    welcomeMessage: "¡Bienvenido al AIquiz!",
    topicPlaceholder: "Tema",
    startButton: "Comenzar",
    loading: "Cargando",
    correctAnswers: "Respuestas Correctas:",
  },
  portuguese: {
    welcomeMessage: "Bem-vindo ao AIquiz!",
    topicPlaceholder: "Tema",
    startButton: "Iniciar",
    loading: "Carregando",
    correctAnswers: "Respostas Corretas:",
  },
  russian: {
    welcomeMessage: "Добро пожаловать в AIquiz!",
    topicPlaceholder: "Тема",
    startButton: "Начать",
    loading: "Загрузка",
    correctAnswers: "Правильных ответов:",
  },
  japanese: {
    welcomeMessage: "AIクイズへようこそ！",
    topicPlaceholder: "トピック",
    startButton: "スタート",
    loading: "読み込み中",
    correctAnswers: "正解数：",
  },
  korean: {
    welcomeMessage: "AI퀴즈에 오신 것을 환영합니다!",
    topicPlaceholder: "주제",
    startButton: "시작",
    loading: "로딩 중",
    correctAnswers: "정답 수:",
  },
  french: {
    welcomeMessage: "Bienvenue sur AIquiz !",
    topicPlaceholder: "Thème",
    startButton: "Démarrer",
    loading: "Chargement",
    correctAnswers: "Réponses Correctes :",
  },
  german: {
    welcomeMessage: "Willkommen beim AIquiz!",
    topicPlaceholder: "Thema",
    startButton: "Start",
    loading: "Laden",
    correctAnswers: "Richtige Antworten:",
  },
  italian: {
    welcomeMessage: "Benvenuti all'AIquiz!",
    topicPlaceholder: "Argomento",
    startButton: "Inizia",
    loading: "Caricamento",
    correctAnswers: "Risposte Corrette:",
  },
  turkish: {
    welcomeMessage: "AIquiz'e hoş geldiniz!",
    topicPlaceholder: "Konu",
    startButton: "Başlat",
    loading: "Yükleniyor",
    correctAnswers: "Doğru Cevaplar:",
  },
  arabic: {
    welcomeMessage: "مرحبًا بك في اختبار AIquiz!",
    topicPlaceholder: "موضوع",
    startButton: "بدء",
    loading: "جار التحميل",
    correctAnswers: "الإجابات الصحيحة:",
  },
  ukrainian: {
    welcomeMessage: "Ласкаво просимо до AIquiz!",
    topicPlaceholder: "Тема",
    startButton: "Почати",
    loading: "Завантаження",
    correctAnswers: "Правильних відповідей:",
  },
  hindi: {
    welcomeMessage: "AIक्विज़ में आपका स्वागत है!",
    topicPlaceholder: "विषय",
    startButton: "शुरू करें",
    loading: "लोड हो रहा है",
    correctAnswers: "सही उत्तर:",
  },
  vietnamese: {
    welcomeMessage: "Chào mừng bạn đến với AIquiz!",
    topicPlaceholder: "Chủ đề",
    startButton: "Bắt đầu",
    loading: "Đang tải",
    correctAnswers: "Câu trả lời đúng:",
  },
};

export default strings;